local_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 3
  publish_frequency: 1
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.075
  footprint_padding: 0.1
  plugins:
   - {name: static_layer, type: "costmap_2d::StaticLayer2"}
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: footprint_layer, type: "costmap_2d::FootprintLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  obstacle_layer:
    observation_sources: laser
    combination_method: 1
    laser: {topic: scan, data_type: LaserScan, expected_update_rate: 3, observation_persistence: 0.0, marking: true, clearing: true}
  static_layer:
    unknown_cost_value: 254
    use_maximum: false
  inflation_layer:
    inflation_radius: 0.9
