%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-trajectory-tracker
Version:        0.11.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS trajectory_tracker package

License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       ros-noetic-dynamic-reconfigure
Requires:       ros-noetic-geometry-msgs
Requires:       ros-noetic-interactive-markers
Requires:       ros-noetic-nav-msgs
Requires:       ros-noetic-neonavigation-common
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-std-srvs
Requires:       ros-noetic-tf2
Requires:       ros-noetic-tf2-geometry-msgs
Requires:       ros-noetic-tf2-ros
Requires:       ros-noetic-trajectory-tracker-msgs >= 0.8.0
BuildRequires:  eigen3-devel
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-dynamic-reconfigure
BuildRequires:  ros-noetic-geometry-msgs
BuildRequires:  ros-noetic-interactive-markers
BuildRequires:  ros-noetic-nav-msgs
BuildRequires:  ros-noetic-neonavigation-common
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-roslint
BuildRequires:  ros-noetic-rostest
BuildRequires:  ros-noetic-std-srvs
BuildRequires:  ros-noetic-tf2
BuildRequires:  ros-noetic-tf2-geometry-msgs
BuildRequires:  ros-noetic-tf2-ros
BuildRequires:  ros-noetic-trajectory-tracker-msgs >= 0.8.0
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Path following control package for wheeled mobile robot

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Mon Nov 08 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.11.2-1
- Autogenerated by Bloom

* Fri Oct 29 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.11.1-1
- Autogenerated by Bloom

* Tue Aug 31 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.11.0-1
- Autogenerated by Bloom

* Mon Jun 21 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.10.11-1
- Autogenerated by Bloom

* Thu Mar 18 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.10.10-1
- Autogenerated by Bloom

* Tue Mar 16 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.10.9-1
- Autogenerated by Bloom

* Wed Mar 10 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.10.8-1
- Autogenerated by Bloom

* Sun Mar 07 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.10.7-1
- Autogenerated by Bloom

* Thu Jan 28 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.10.6-1
- Autogenerated by Bloom

* Fri Dec 25 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.10.5-1
- Autogenerated by Bloom

* Thu Nov 12 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.10.4-1
- Autogenerated by Bloom

* Thu Oct 22 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.10.3-1
- Autogenerated by Bloom

* Thu Oct 08 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.10.2-1
- Autogenerated by Bloom

* Wed Aug 26 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.10.1-1
- Autogenerated by Bloom

* Fri Aug 07 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.10.0-1
- Autogenerated by Bloom

* Thu Jul 16 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.9.1-1
- Autogenerated by Bloom

* Thu Jul 02 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.9.0-1
- Autogenerated by Bloom

* Tue Jun 16 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.8.8-1
- Autogenerated by Bloom

* Fri May 22 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.8.7-1
- Autogenerated by Bloom

* Fri May 15 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.8.6-1
- Autogenerated by Bloom

* Mon May 04 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.8.5-1
- Autogenerated by Bloom

* Thu Apr 30 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.8.4-1
- Autogenerated by Bloom

* Sun Apr 26 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.8.3-1
- Autogenerated by Bloom

